default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV['DATABASE_URL']&.gsub('development', 'test') %>

production:
  <<: *default
